---
- name: Create AutomationOrchestrator instance
  kubernetes.core.k8s:
    state: present
    template: automation_orchestrator.yaml.j2
  register: r_ao
  until: r_ao is success
  retries: 5
  delay: 30

- name: Wait for AutomationOrchestrator to be Ready
  kubernetes.core.k8s_info:
    api_version: aap.ansible.com/v1alpha1
    kind: AutomationOrchestrator
    name: "{{ ocp4_workload_automation_orchestrator_name }}"
    namespace: "{{ ocp4_workload_automation_orchestrator_namespace }}"
  register: r_ao_instance
  retries: "{{ ocp4_workload_automation_orchestrator_instance_wait_retries }}"
  delay: "{{ ocp4_workload_automation_orchestrator_instance_wait_delay }}"
  until:
    - r_ao_instance.resources | length > 0
    - r_ao_instance.resources[0].status is defined
    - r_ao_instance.resources[0].status.conditions is defined
    - >-
      (r_ao_instance.resources[0].status.conditions
       | selectattr('type', 'equalto', 'Ready')
       | map(attribute='status') | list | first | default('False')) == 'True'

- name: Set AO URL fact
  ansible.builtin.set_fact:
    _ocp4_workload_automation_orchestrator_ao_url: >-
      https://{{ _ocp4_workload_automation_orchestrator_ingress_host }}

- name: Get initial admin password secret
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Secret
    name: "{{ ocp4_workload_automation_orchestrator_name }}-initial-admin-password"
    namespace: "{{ ocp4_workload_automation_orchestrator_namespace }}"
  register: r_ao_admin_secret

- name: Set admin password fact
  when: r_ao_admin_secret.resources | length > 0
  ansible.builtin.set_fact:
    _ocp4_workload_automation_orchestrator_admin_password: >-
      {{ r_ao_admin_secret.resources[0].data.password | b64decode }}
  no_log: true

- name: Publish Automation Orchestrator access info
  agnosticd.core.agnosticd_user_info:
    msg: >-
      Automation Orchestrator is available at {{ _ocp4_workload_automation_orchestrator_ao_url }}
      with username 'admin' and password
      '{{ _ocp4_workload_automation_orchestrator_admin_password }}'.
    data:
      ao_url: "{{ _ocp4_workload_automation_orchestrator_ao_url }}"
      ao_admin_user: admin
      ao_admin_password: "{{ _ocp4_workload_automation_orchestrator_admin_password }}"
