---
namespace: "intro_ao_workshop"
name: "automation"
version: "1.0.0"
readme: README.md
authors:
  - "rlopez133 <rlopez@redhat.com>"
description: "Starter collection for this project's custom Ansible automation."
license: []
repository: "https://github.com/rhpds/intro-ao-workshop"
