#SPDX-License-Identifier: MIT-0
galaxy_info:
  author: rlopez133
  description: Deploys and configures Ansible Automation Orchestrator on OpenShift Container Platform 4
  license: GPL-2.0-or-later
  min_ansible_version: 2.9
  galaxy_tags: []
dependencies: []
